config/routes.rb
  Instacopy::Application.routes.draw do
  devise_for :users

  root 'posts#index'

  resources :posts do
    resources :comments, :only => :create
    resources :photos, :only => :create
  end
  resources :users, :only => :show   

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
   belongs_to :post

end

app/models/photo.rb
class Photo < ActiveRecord::Base
	belongs_to :post
	belongs_to :user


	 mount_uploader :picture, PictureUploader  

      
      
     
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	has_many :comments
	has_many :photos

	validate :title, presence => true, length: { minimun: 3 }
	
	validate :description, presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable     
         
  has_many :posts 
  has_many :comments   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!
	
	def create
		@post = Post.find(params[:post_id])
		@post.comments.create(comment_params.merge(:user => current_user))
		redirect_to post_path(@post)
	end	

	private 

	def comment_params
		params.require(:comment).permit(:message)
	end	
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
	 before_action :authenticate_user!

	def create
		@post = Post.find(params[:post_id])
		@post.photos.create(photo_params)
		redirect_to post_path(@post)

	end	

	private 

	def photo_params
			params.require(:photo).permit(:picture, :post_id)
	end 
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	 before_action :authenticate_user!, :only => [:new, :create, :update, :destroy]

	def index
		@posts = Post.all.page(params[:page]).per(10)
	end	

	def new
		@post = Post.new
	end	

	def create
		@post = current_user.posts.create(post_params)
		if @post.valid?
			redirect_to root_path
		else 
			render :new, :status => :unprocessable_entity
		end		
	end	

	def show
		@post = Post.find(params[:id])
		@comment = Comment.new
		@photo = Photo.new
	end	

	def edit
		@post = Post.find(params[:id])
	end	

	def update
		@post = Post.find(params[:id])

		if @post.user != current_user
			return render :text => 'Not allowed', :status => :forbidden
		end

		@post.update_attributes(post_params)
		if @post.valid?
			redirect_to root_path
		else 
			render :edit, :status => :unprocessable_entity
		end	
	end	

	def destroy
		@post = Post.find(params[:id])
		if @post.user != current_user
			return render :text => 'Not allowed', :status => :forbidden
		end
		
		@post.destroy
		redirect_to root_path	
	end	


	private

	def post_params
		params.require(:post).permit(:title, :description)
	end	

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def show
		@user = User.find(params[:id])
	end	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Instacopy</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <%= link_to 'Instacopy', root_path, :class => 'navbar-brand' %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to new_post_path do %>
          <i style="font-size:3.5em;" class="glyphicon glyphicon-send"></i>
          
          <% end %>
        </li>
        <% if user_signed_in? %>
          <li>
            <%= link_to user_path(current_user) do %>
            <i style="font-size:3.5em;" class="glyphicon glyphicon-user"></i>
            
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, :method => :delete  do %>
            <i style="font-size:3.5em;" class="glyphicon glyphicon-eject"></i>
            
            <% end %>
          </li>
        <% else %>
          <li>
            <%= link_to  new_user_session_path do %>
            <i style="font-size:3.5em;" class="glyphicon glyphicon-inbox"></i>
            
            <% end %>
          </li>  
          <li>
            <%= link_to new_user_registration_path  do %>
            <i style="font-size:3.5em;" class="glyphicon glyphicon-pencil"></i>
            
            <% end %>
          </li> 
        <% end %>  
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<% if notice.present? %>
  <p class="alert alert-info"><%= notice %></p>
<% end %>
<% if alert.present? %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>


<%= yield %>

</body>
</html>

app/views/posts/edit.html.erb
<div class="box-each col-xs-12">
	<h1>Edit your Post</h1>
	<%= simple_form_for @post do |f| %>
		<%= f.input :title %>
		<%= f.input :description %>
		<br />
		<%= f.submit :Update, :class => 'btn btn-primary' %>
	<% end %>	
</div>

app/views/posts/index.html.erb
<% @posts.reverse.each do |post| %>
	<div class="box-in-posts col-xs-12">
		<h2><%= link_to post.title, post_path(post) %></h2><br />
		<p><%= post.description %></p>

		<% if post.user.present? %>
			<b><small><%= post.user.email %></small></b>
		<% end %>	
		<div class='clear'></div>
		<br />

		<% if post.photos.present? %>
			<div class="col-xs-12">	
				<% if post.photos.last.picture.present? %>
					<div class="container-fluid">
						<div class="img-responsive-parent-1">							
							<%= image_tag post.photos.last.picture, :class => 'img-responsive' %>
						</div>
					</div>		
				<% end %>
			</div>		
		<% end %>

		<% if post.comments.present? %>
			<div class="col-xs-12">
				<blockquote>
					<%= post.comments.last.message %>
					<small><%= post.comments.last.user.email %></small> 
				</blockquote>
			</div>	
		<% end %>		
	</div>	
<% end %>	

<div class="clear"></div>			

<div class="col-xs-12 text-center">
	<%= paginate @posts %>	
</div>

app/views/posts/new.html.erb
<div class="box-in-posts col-xs-10 col-xs-offset-1">
	<h1>Post something cool here</h1>
	<%= simple_form_for @post do |f| %>
		<%= f.input :title %>
		<%= f.input :description %>
		<br />
		<%= f.submit 'Create', :class => 'btn btn-primary' %>
	<% end %>	
</div>	

app/views/posts/photos.html.erb
<div class="box-in-posts col-xs-10 col-xs-offset-1">
	<h1>Upload an image</h1>
	<%= simple_form_for @photo :url => post_comments_path(@post) do |f| %>
		<%= f.input :picture %>	
		<br />
		<%= f.submit 'Create', :class => 'btn btn-success' %>
	<% end %>	
</div>	

app/views/posts/show.html.erb
<div class="box-each col-xs-12">
	<h1><%= @post.title %></h1>
	<br />
	<p><%= @post.description %></p>
	<br />
	<br />
	<div class='pull-right'>
	<% if current_user && current_user == @post.user %>	
		
		<%= link_to 'Edit post', edit_post_path(@post), :class => 'btn btn-primary' %>
		<%= link_to 'Destroy', post_path(@post), :method => :delete, :data => {:confirm => 'Are you sure?'}, :class => 'btn btn-danger' %>	
		<button class="btn btn-md" data-toggle="modal" data-target="#Photo">
					Add a photo
		</button>	
	<% end %>	
	</div>
</div>

<div class='clear'></div>
<br />

<!-- Modal for Photos -->
<div class="modal fade" id="Photo" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title" id="myModalLabel">Upload an image</h4>
			</div>
			<%= simple_form_for @photo, :url => post_photos_path(@post) do |f| %>
				<div class="modal-body">  	
					<%= f.input :picture %>
				</div>	
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>    
					<%= f.submit "Upload it!", :class => 'btn btn-success' %>  
				</div>
			<% end %>
		</div>
	</div>
</div>
<br />

<div class='clear'></div>
<br />
		  
<!-- Modal for comments -->
<div class="modal fade" id="Comment" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Add comment</h4>
      </div>
      <%= simple_form_for @comment, :url => post_comments_path(@post) do |f| %>
      	<div class="modal-body">  	
	  			<%= f.input :message %>
			 </div>	
			<div class="modal-footer">
         	<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>    
         	<%= f.submit "Add a comment", :class => 'btn btn-primary' %> 
     		</div>
      <% end %>
    </div>
  </div>
</div>

<div class="big-box col-xs-12">	
	<div class="container-fluid">
		<div class="img-responsive-parent">	
			<% @post.photos.each do |photo| %>
				<%= image_tag photo.picture, :class => 'img-responsive' %>
			<% end %>
		</div>	
	</div>		
	<br />
	<br />
	<div class="col-xs-10 col-xs-offset-1">
		<h1 class="pull-left">Comments</h1>
		<!-- Modal button for comments -->
		<button class="btn btn-primary btn-lg pull-right" data-toggle="modal" data-target="#Comment">Add comment</button>
	</div>

	<% @post.comments.each do |comment| %>
	  <div class="col-xs-10 col-xs-offset-1">
		<div>
			<blockquote>
				<b><%= comment.message %></b>
				<small><%= comment.user.email %></small>
			</blockquote>
		</div>		
	  </div>		
	<% end %>	
</div>

app/views/users/show.html.erb
<div class="box-profile">	
	<div class="col-xs-1 pull-right">
		<%= image_tag 'user.png' %>
	</div>

	<div class="col-xs-3">	
		<h1><%= @user.email %></h1>
		<h3>Active since: <%= @user.created_at.strftime("%B/%d/%Y") %></h3>
		<h4><%= @user.comments.count %> total comments</h4>
	</div>	
<div class="clear"></div>
</div>	

<br />
<h1 class="text-center">Comments made</h1>
<br/ >
<% @user.comments.each do |comment| %>
	<div class="col-xs-12">
		<h2 class="text-center"><%= link_to comment.post.title, post_path(comment.post) %><h2/> 
	    <blockquote>
	      <%= comment.message %>
	      <small><%= comment.user.email %></small>
	    </blockquote>
  </div>
<% end %>

<div class="clear"></div>
<br /><br />
<h1 class="text-center">Posted</h1>
<br /><br />
<% @user.posts.each do |post| %>
	<div class="box-in-posts-1 col-xs-10 col-xs-offset-1">
		<h2><%= link_to post.title, post_path(post) %></h2><br />
		<p><%= post.description %></p><br />
		<% if post.user.present? %>
			<small><%= post.user.email %></small>
		<% end %>	
	</div>	
<% end %>	